### ISSUE TITLE
Publication API

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#121]
# Publication API

Add a mechanism for managing deployments within Orchid

---

Right now, Orchid just generates your site and then is done with it. If you want to deploy it somewhere, you would need to either manually upload the resulting files somewhere, use a dedicated platform like Netlify to run the build and then deploy the result, or run some kind of external shell script to upload the files where you want. In all cases, this would mean you'd have to change your method of deployment based on where you are deploying _to_ and where you're deploying _from_. 

A solution to this problem is to open up a first-class deployment API within Orchid, that runs as part of a new `deploy` task. This task would allow one to register one or more "deployers" that take the resulting Orchid site and do something with it. This should support using multiple deployers as part of one deployment phase, and should allow for a site to be deployed to a versioned directory of that target, rather than replacing the entire site as nearly all CI tools do currently. It should also contain helpful APIs for locating/managing the resulting site's files, including easy git and zip support.

A new plugin should be created which comes with deployers for Github Pages, and Netlify, but the community is free to build their own deployers as well. I would also do S3, but I have never used S3 and I am unsure of the amount of work that would require when I personally have no use for it, and would rather build this when requested or open this up for contribution.

**To-Do**

- [x] New `deploy` task, that runs a single build followed by a single deploy. This task is run on its own and is not considered a dry deploy by default, but a command-line flag can make this a dry deploy. 
- [x] Create a `deploy` command, that runs a single deploy. This command should be able to be invoked from the server and from the `interactive` task, and is considered a dry deploy by default.
- [x] Create a `DeployService` which has the APIs needed for hooking into deployments.
- [x] Create an `OrchidDeployer` class that implements a deployment step. The way deployers are managed should be nearly identical to `OrchidGenerators` in that they are ordered, they have options extracted by default, and they are can be turned on/off from `config.yml` options outside the control of the generator itself.
- [x] Set up deployment pipeline as a ModularList for fine-grained control and potential repeated tasks with different data
- [x] Create several built-in deployers/optimizers
  - [x] Simple shell script execution
  - [x] Github Pages
  - [x] Netlify 
  - [ ] Minify JS/CSS/HTML?
