### ISSUE TITLE
Replace "magic" includes with TemplateTags

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#138]
There are lots of places in Theme layouts and other places where core theme logic is simple implemented as an `include`. This makes it difficult to keep track of which includes implement core Orchid features, and which are simply modularization of the theme, and leaves absolutely no auto-generated documentation about the proper way to build a theme.

Instead of including these core templates as raw `include` statements, custom TemplateTags should be built in the `OrchidCore` module, and those can be used instead. These will be auto-documented in the user's Admin area, and will make it easier to prescribe common pieces of Orchid theme setup.

**To-Do**

- [x] Replace `{% include 'includes/head' %}` with `{% head %}`, which includes various SEO meta tags, page title, etc.
- [x] Replace `{% include 'includes/styles' %}` with `{% styles %}`, which renders the list of stylesheets for the current page. 
- [x] Replace `{% include 'includes/scripts' %}` with `{% scripts %}`, which renders the list of scripts for the page. This should include a parameter for filtering scripts to the `head`, or beginning or end of `<body>`
- [ ] Replace `{% include '?trackingBodyStart' %}` with `{% tracking 'BodyStart' %}`, etc.
- [ ] Replace `{% include 'includes/componentHolder' with {"componentHolder": page.components} %}` with `{% components page.components %}`.
- [x] In addition, make a `{% page %}` tag which wraps `{% components page.components %}`, which should make it possible (to some extent) to reuse themes from OctoberCMS with very little changes.
