### ISSUE TITLE
Add Wiki plugin adapters for common wiki repo formats

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#253]
Github, Gitlab, Bitbucket, Azure DevOps, and likely others, all support some form of git-repo-backed Wiki. Rather than forcing users of those platforms to convert those wikis to Orchid's format, why not provide adapters to build Orchid's wikis based on their formats? 

By default, Orchid will use the current format for building wikis, of parsing a `summary.md` file and building the tree of its links. Instead, you should be able to set up each section's adapter to one of the available adapters. Each adapter is free to load its Wiki content in whatever way it needs to.

For the git-based wikis, this will involve cloning the project at runtime, and then the adapter will determine how to build the hierarchy from its content.

This should go hand-in-hand with #254 , as these wiki adapters should be created as part of those integration projects.

**To-do**

- [x] Modularize wiki creation so that the current method is just the `orchid` adapter. Also, add a base class for a git-based adapter, so the other adapters only need to worry about file structure
- [x] Create `github` adapter for [GitHub Wikis](https://help.github.com/en/articles/documenting-your-project-with-wikis)
- [x] Create `gitlab` adapter for [GitLab Wikis](https://docs.gitlab.com/ee/user/project/wiki/)
- [ ] Create `bitbucket` adapter for [Bitbucket Wikis](https://confluence.atlassian.com/bitbucket/wikis-221449748.html)
- [ ] Create `azure` adapter for [Azure DevOps Wikis](https://azure.microsoft.com/en-ca/services/devops/wiki/)
