### ISSUE TITLE
Create "integrations" projects

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#254]
Right now, service-specific functionality is kind-of sprinkled throughout core and the various plugins, such as the Github Pages Publisher being in OrchidCore while Github Releases Publisher is in OrchidChangelog. Instead, let's make a new "type" of plugin for `integrations` that is similar to how `languageExtensions` are currently managed, but are able to depend on anything in `plugins`.

We can then move the service-specific features out of core and plugins into these integrations, so that everything is grouped together as it should be. 

This should go hand-in-hand with #253, as those wiki adapters should be created as part of the integration projects.

**To-Do**

- [x] Make new `integrations` plugin type, and enforce their documentation 
- [x] Set up `OrchidGithub` with:
    - `GithubPagesPublisher` (depends on `OrchidCore`)
    - `GithubReleasesPublisher`  (depends on `OrchidChangelog`)
    - `GithubWikiAdapter`  (depends on `OrchidWiki`)
- [x] Set up `OrchidNetlify` with:
    - `NetlifyPublisher` (depends on `OrchidCore`)
    - maybe move the NetlifyCMS plugin here?
- [x] Set up `OrchidGitlab` with:
    - `GitlabWikiAdapter`  (depends on `OrchidWiki`)
    - `GitlabPagesPublisher`  (depends on `OrchidCore`) to deploy to [GitLabPages](https://about.gitlab.com/product/pages/)
- [ ] Set up `OrchidBitbucket` with:
    - `BitbucketWikiAdapter`  (depends on `OrchidWiki`)
    - `BitbucketCloudPublisher`  (depends on `OrchidCore`) to deploy to [Bitbucket Cloud](https://confluence.atlassian.com/bitbucket/publishing-a-website-on-bitbucket-cloud-221449776.html)
- [ ] Set up `OrchidAzure` with:
    - `AzureDevopsWikiAdapter`  (depends on `OrchidWiki`)
