### ISSUE TITLE
Break Gradle Plugin into multiple plugins and add support for other documentation tool runners

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#30]
Gradle plugins (in `buildSrc`) should include:
- The core plugin to run Orchid from command line
- Plugin to run Orchid from Javadoc
- Additional plugins for other purposes, such as Dokka (Kotlin), Scaladoc, etc. Integrating Orchid with those tools should have an accompanying Orchid Plugin which implements the same or similar functionality as the Gradle tool it is replacing, but embedded within Orchid.

Each plugin should be distributed as its own plugin on the Gradle Plugins Portal. All "additional" plugins should either require the core plugin or have the core plugin bundled with it.

Also, add Gradle plugin to run Orchid from Kotlin's "Javadoc" Dokka. May need to reach out to the Dokka team to find the simplest way to integrate Dokka and Orchid, hopefully without re-inventing their build tool.

**Subtasks**

- [x] Move Javadoc to separate plugin
- [x] Create Dokka plugin (even if it just replaces the Dokka task without generating code docs at the moment)
- [ ] Create Android-based Orchid plugin (rather than java-based) 
- [ ] Create Android-based Javadoc plugin (rather than java-based) 
- [ ] Create Maven Orchid plugin
- [ ] Create Maven Javadoc plugin

**Comment by cjbrooks12** [comment]
After enough frustration with running Orchid as a Doclet, I updated the Orchid Javadoc plugin to get the Javadoc model directly rather than going through the official javadoc CLI to start Orchid. This means we no longer need a dedicated gradle plugin to use Javadoc in Orchid.

Updated checklist:

- [ ] Create Dokka Orchid plugin. I have gotten it working by manipulating the output from the Gradle task ([see here](https://github.com/JavaEden/specifikation)), but want to have it load the documentation model from within Orchid and not need the Gradle plugin at all.
- [ ] Create Android-based Orchid plugin (rather than java-based) 
- [ ] Create Maven Orchid plugin
- [ ] Have the bundle projects also produce a fat-jar [Capsule](https://github.com/puniverse/capsule), so Orchid can be easily run directly as a CLI tool, but i want them to load additional jars relative to the capsule so that additional plugins can be dropped into a folder and discovered automatically
- [ ] Create a simple [kscript](https://github.com/holgerbrandl/kscript) and host it as a Gist, so that Orchid can be easily run and customized with a script, without needing Gradle
